---
title: "DATA607 - Spam or Ham"
author: "Chris G. Martin"
date: "April 8, 2016"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: cerulean
    highlight: kate
---

#Predicting emails as SPAM or HAM (not-spam)

##OVerview

Emails: one of the most useful communication tools available to everyone with an internet connection. Unfortunately, everyone with an internet connection can use it, including robots. Our goal in this exercize is to identify the "good" emails (**ham**) from the "bad" (**spam**--which is actually quite tasty sometimes) using sets of already identified emails (our "training" documents), and "predict" whether or not a new document is spam.

So let's start by loading our necessary packages. I'm using a new (for me) package called *pacman* to load the libraries. It seems an easier way to install and load multiple packages at the same time[1], and anything that saves Data Scientists' time is worth investigating.

```{r}
pacman::p_load(knitr, tm, RTextTools)
```












[1] more information on pacman can be found here: https://cran.r-project.org/web/packages/pacman/vignettes/Introduction_to_pacman.html